language: node_js
branches:
  only:
  - master
node_js:
- lts/*
cache:
  directories:
    - "$HOME/.npm"
services:
  - redis
  - docker
install:
- npm ci
before_script:
- NODE_ENV=test npx sequelize-cli db:migrate
- npm run build
script:
- npm run lint-ci
- npm test
after_script:
- bash <(curl -s https://codecov.io/bash)
- echo "$DOCKER_PASSWORD" | docker login -u "dyc3" --password-stdin
- docker-compose -f docker/docker-compose.yml up -d --build
- docker commit opentogethertube opentogethertube
- docker tag opentogethertube dyc3/opentogethertube:latest
- docker push dyc3/opentogethertube:latest
