global:
  scrape_interval: "1m"
scrape_configs:
  - job_name: OpenTogetherTube
    metrics_path: /api/status/metrics
    scheme: http
    static_configs:
      - targets:
          - opentogethertube.com