name: CI/CD

on:
  pull_request:
  push:
    branches:
    - master
    - main
    paths-ignore:
    - '.vscode/**'
    - 'docs/**'
    - 'env/**'
    - '**/*.md'

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v1
    - name: Get npm cache directory
      id: npm-cache
      run: |
        echo "::set-output name=dir::$(npm config get cache)"
    - uses: actions/cache@v1
      with:
        path: ${{ steps.npm-cache.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        check-latest: true
    - run: npm ci
    - run: npm run lint-ci
      env:
        NODE_ENV: production

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    continue-on-error: true
    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
            - 6379:6379

    steps:
    - uses: actions/checkout@v1
    - name: Get npm cache directory
      id: npm-cache
      run: |
        echo "::set-output name=dir::$(npm config get cache)"
    - uses: actions/cache@v1
      with:
        path: ${{ steps.npm-cache.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        check-latest: true
    - run: npm ci
    - run: npx sequelize-cli db:migrate
      env:
        NODE_ENV: test
    - run: npm run build --if-present
    - run: npm run test-unit-client
    - run: npm run test-unit-server
      env:
        REDIS_HOST: localhost
        REDIS_PORT: 6379
    # - run: npx sequelize-cli db:migrate
    # - run: npm run test-e2e
    #   env:
    #     REDIS_HOST: localhost
    #     REDIS_PORT: 6379
  deploy-docker:
    runs-on: ubuntu-latest
    name: Deploy docker image
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: [test, lint]
    steps:
    - uses: actions/checkout@v1
    - name: Log in to Dockerhub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "dyc3" --password-stdin
        touch env/production.env
    - name: Build image
      run: |
        docker-compose -f docker/docker-compose.yml up -d --build
        docker commit opentogethertube opentogethertube
        docker-compose -f docker/docker-compose.yml down
        docker tag opentogethertube dyc3/opentogethertube:latest
    - name: Push to Dockerhub
      run: docker push dyc3/opentogethertube:latest